//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WishlistApp3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class price
    {
        public long priceID { get; set; }
        public long itemID { get; set; }
        public string theURL { get; set; }
        public string website { get; set; }
        public Nullable<decimal> price1 { get; set; }
    
        public virtual item item { get; set; }
    }
}
